repos:
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      types: ["python"]
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
    - id: yapf
      types: ["python"]
      additional_dependencies: ["toml"]
- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout
      types: ["jupyter"]
      args: ['--strip-empty-cells',
             '--extra-keys', 'metadata.language_info.version cell.metadata.jp-MarkdownHeadingCollapsed']
