name: Docs

on:
  workflow_dispatch:
    inputs:
      publish:
        default: false
        type: boolean
      release:
        default: false
        type: boolean
  workflow_call:
    inputs:
      publish:
        default: false
        type: boolean
      release:
        default: false
        type: boolean

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt install --yes graphviz pandoc
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/ci.txt
      - run: tox --skip-pkg-install -e docs scippnexus==${GITHUB_REF_NAME}
        if: ${{ inputs.publish && inputs.release }}
      - run: tox --skip-pkg-install -e docs scippnexus
        if: ${{ inputs.publish && !inputs.release }}
      - run: tox -e docs
        if: ${{ !inputs.publish }}
      - uses: actions/upload-artifact@v3
        with:
          name: html
          path: html/

      - uses: JamesIves/github-pages-deploy-action@v4.3.4
        if: ${{ inputs.publish }}
        with:
          branch: gh-pages
          folder: html
          target-folder: ${{ inputs.release && format('release/{0}', github.ref_name) || '' }}
          single-commit: true
          clean-exclude: release
          ssh-key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
