name: Docs

on:
  workflow_dispatch:
    inputs:
      publish:
        default: false
        type: boolean
      version:
        default: ''
        required: false
        type: string
  workflow_call:
    inputs:
      publish:
        default: false
        type: boolean
      version:
        default: ''
        required: false
        type: string

env:
  VERSION: ${{ inputs.version }}

jobs:
  docs:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt install --yes graphviz pandoc
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements/ci.txt
      - run: tox --skip-pkg-install -e docs scippnexus==${VERSION}
        if: ${{ inputs.publish }}
      - run: tox -e docs
        if: ${{ !inputs.publish }}
      - uses: actions/upload-artifact@v3
        with:
          name: html
          path: html/

  docs-publish:
    name: Publish documentation
    if: ${{ inputs.publish }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'gh-pages'
      - name: Manage folders
        id: manage-folders
        run: |
          export target_folder=${VERSION%.*}
          if [ ${VERSION##*.} -eq 0 ]
          then
            git mv release/stable release/$(cat stable-version)
            echo $target_folder > stable-version
            export target_folder=stable
          fi
          echo "::set-output name=folder::$target_folder"
      - uses: stefanzweifel/git-auto-commit-action@v4

      - uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          branch: gh-pages
          folder: html
          target-folder: ${{ format('release/{0}', steps.manage-folders.folder) }}
          #target-folder: ${{ inputs.release && format('release/{0}', github.ref_name) || '' }}
          single-commit: true
          ssh-key: ${{ secrets.GH_PAGES_DEPLOY_KEY }}
